In [1]:
import numpy as np

In [2]:
mx_1 = np.array([[1,1,1],[1,1,1],[1,1,1]])
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [4]:
mx_2 = np.ones(5) # for creat 1 matrix single value only assingn colum(5)
print(mx_2)

[1. 1. 1. 1. 1.]


In [ ]:
mx_3 = np.ones((3,4))  # for creat 1 matrix (row,colum)
print(mx_3)

In [11]:
mx_4 = np.ones((3,4),dtype=int) # for creat 1 matrix ((row,colum), datatye)
print(mx_4)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [15]:
mx_5 = np.zeros((3,4)) # creat zero matrix (row,colum) 
print(mx_5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
mx_6 = np.empty((3,4))  # creat empty matrix (row,colum) 
print(mx_6)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
